# Generated by Django 4.2.7 on 2023-11-21 03:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Crypto', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Coin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('symbol', models.CharField(max_length=10)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('market_cap', models.DecimalField(decimal_places=2, max_digits=15)),
                ('volume_24h', models.DecimalField(decimal_places=2, max_digits=15)),
                ('change_24h', models.DecimalField(decimal_places=2, max_digits=5)),
            ],
        ),
    ]
