<<<<<<< HEAD
# Generated by Django 4.2.4 on 2023-11-26 19:26
=======
# Generated by Django 4.2.7 on 2023-11-21 04:30
>>>>>>> RitulWithMaster

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Crypto', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricalPrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cryptocurrency', models.CharField(max_length=100)),
                ('price', models.DecimalField(decimal_places=5, max_digits=20)),
                ('date', models.DateField()),
            ],
        ),
    ]
