# Generated by Django 4.2.7 on 2023-11-27 20:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Crypto', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Coin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('symbol', models.CharField(max_length=10)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('market_cap', models.DecimalField(decimal_places=2, max_digits=15)),
                ('volume_24h', models.DecimalField(decimal_places=2, max_digits=15)),
                ('change_24h', models.DecimalField(decimal_places=2, max_digits=5)),
            ],
        ),
        migrations.CreateModel(
            name='CryptoAsset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('price', models.DecimalField(decimal_places=5, max_digits=20)),
                ('high', models.DecimalField(blank=True, decimal_places=5, max_digits=20, null=True)),
                ('low', models.DecimalField(blank=True, decimal_places=5, max_digits=20, null=True)),
                ('price_change_24h', models.DecimalField(blank=True, decimal_places=5, max_digits=20, null=True)),
                ('price_change_percentage_24h', models.DecimalField(blank=True, decimal_places=5, max_digits=20, null=True)),
                ('market_cap', models.DecimalField(blank=True, decimal_places=5, max_digits=20, null=True)),
                ('volume_24h', models.DecimalField(blank=True, decimal_places=5, max_digits=20, null=True)),
                ('circulating_supply', models.DecimalField(blank=True, decimal_places=5, max_digits=20, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='HistoricalPrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cryptocurrency', models.CharField(max_length=100)),
                ('price', models.DecimalField(decimal_places=5, max_digits=20)),
                ('date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='TrendingCrypto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('symbol', models.CharField(max_length=10, unique=True)),
                ('current_price', models.FloatField()),
            ],
        ),
        migrations.RemoveField(
            model_name='userdetails',
            name='profile_picture',
        ),
        migrations.AddField(
            model_name='userdetails',
            name='identity',
            field=models.FileField(blank=True, null=True, upload_to='user_identities/'),
        ),
        migrations.AddField(
            model_name='userdetails',
            name='identity_uploaded',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bio', models.TextField()),
                ('avatar', models.ImageField(upload_to='avatars/')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserIdentity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identity_uploaded', models.BooleanField(default=False)),
                ('identity_photo', models.ImageField(blank=True, null=True, upload_to='identity_photos/')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='Crypto.userdetails')),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('content', models.TextField()),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Crypto.userprofile')),
            ],
        ),
    ]
