# Generated by Django 4.2.7 on 2023-11-28 03:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Crypto', '0002_coin_cryptoasset_historicalprice_trendingcrypto_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdetails',
            name='profile_photo',
            field=models.ImageField(blank=True, null=True, upload_to='user_profiles/'),
        ),
        migrations.AlterField(
            model_name='useridentity',
            name='identity_photo',
            field=models.ImageField(blank=True, null=True, upload_to='user_profiles/'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='avatar',
            field=models.ImageField(upload_to='profile_photos/'),
        ),
    ]
