# Generated by Django 4.2.7 on 2023-11-21 05:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Crypto', '0003_cryptoasset'),
    ]

    operations = [
        migrations.AddField(
            model_name='cryptoasset',
            name='icon_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
