# Generated by Django 4.2.7 on 2023-11-28 03:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Crypto', '0003_userdetails_profile_photo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='avatar',
            field=models.ImageField(upload_to='user_profiles/'),
        ),
    ]
