# Generated by Django 4.2.7 on 2023-11-21 05:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Crypto', '0004_cryptoasset_icon_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cryptoasset',
            name='icon_url',
        ),
    ]
