# Generated by Django 4.2.7 on 2023-11-28 03:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Crypto', '0004_alter_userprofile_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useridentity',
            name='identity_photo',
            field=models.ImageField(blank=True, null=True, upload_to='user_identities/'),
        ),
    ]
