# Generated by Django 4.2.7 on 2023-11-26 20:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Crypto', '0002_coin'),
        ('Crypto', '0006_userprofile_post'),
    ]

    operations = [
    ]
