# Generated by Django 4.2.7 on 2023-11-26 21:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Crypto', '0007_merge_0002_coin_0006_userprofile_post'),
    ]

    operations = [
        migrations.CreateModel(
            name='TrendingCrypto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('symbol', models.CharField(max_length=10, unique=True)),
                ('current_price', models.FloatField()),
            ],
        ),
    ]
