# Generated by Django 4.2.7 on 2023-11-27 00:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Crypto', '0009_useridentity'),
    ]

    operations = [
        migrations.AddField(
            model_name='useridentity',
            name='identity_photo',
            field=models.ImageField(blank=True, null=True, upload_to='identity_photos/'),
        ),
    ]
