# Generated by Django 4.2.7 on 2023-11-27 00:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Crypto', '0010_useridentity_identity_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdetails',
            name='identity',
            field=models.FileField(blank=True, null=True, upload_to='user_identities/'),
        ),
        migrations.AddField(
            model_name='userdetails',
            name='identity_uploaded',
            field=models.BooleanField(default=False),
        ),
    ]
