# Generated by Django 4.2.5 on 2023-11-29 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Crypto', '0012_transactions'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdetails',
            name='profile_picture',
            field=models.ImageField(default='profile_pictures/default.jpg', upload_to='profile_pictures/'),
        ),
    ]
